name: Deploy Frontend

on:
  push:
    branches:
      - master # 你要部署的分支，通常是 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      #     cache: pnpm # 如果你用 npm 就改成 npm

      - name: pwd
        run: pwd

      - name: version
        run: node -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Vue CLI / Vite / React 默认打包目录
